name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Set Test Title
      run: |            
        echo "title=Test Run ${{github.run_number}}" >> $GITHUB_ENV
        echo "file_name:=TestReport.${{github.run_number}}.md" >> $GITHUB_ENV
    - name: Test
      run: dotnet test --no-restore --no-build --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'Test Run'
        path: ${{github.workspace}}/**/Test*.md
